### PR TITLE
Plugins api, resolves #11

### LINKED ISSUE #11: plugin api
I'm thinking for it. I guess that is also in your mind because I seen `github-base` org.

It should be something that you can add only custom methods to the base.
For example

``` js
var Github = require('github-base')
var github = new Github()
var  fork = require('github-base-fork')

var app = github.use(fork())

// https://developer.github.com/v3/repos/forks/#create-a-fork
app.fork('user/repo', cb)

// https://developer.github.com/v3/repos/forks/#list-forks
app.forks('user/repo', cb) // list forks
```

and for other API endpoints.

Another plugin can be only handling all "creating" things like this one ([i've did it before few months](https://github.com/tunnckoCore/github-create))

``` js
var Github = require('github-base')
var github = new Github()
var  create = require('github-base-create')
var  list = require('github-base-list')

var app = github.use(create()).use(list())

// https://developer.github.com/v3/issues/#create-an-issue
app.issue('user/repo') // or maybe better would be `app.create.issue`
app.issues('user/repo') // => list repo issues

// https://developer.github.com/v3/issues/labels/#create-a-label
app.label('user/repo')
app.labels('user/repo') // => list repo labels

// https://developer.github.com/v3/repos/#create
app.repo('user/repo')
app.repos('user')  // => list user repos
```

and etc?

I think we should start it in some point in future. If you thought it, count me in `github-base` org. :)

/cc but we should finalize #7 before all. Btw, today I playing with that and basically all works, except `.getAll` thing.

### PR DESCRIPTION
**Pull request by tunnckoCore**
as #11

### CODE REVIEW

**Comment by tunnckoCore** [comment]
maybe should close #12 ? lol and just merge this if not a problem or to separate them? it seems that i made some mistake

**Comment by jonschlinkert** [comment]
sorry I was a little confused by your previous comment, and forgot to follow up ...

> maybe should close #12 ? lol and just merge this if not a problem or to separate them? it seems that i made some mistake

were you saying this pr, 13, is correct? I will review but wanted to clarify first

**Comment by tunnckoCore** [comment]
yea, both PRs are okey, but only this can (need to) be merged.

edit: i've just forgot to create new branch for the "externalize `.requestAll`" initally, so `plugins-api` branch (this pr) is on top of #12 not on top of current master.

**Comment by jonschlinkert** [comment]
@doowb do you want to merge?

**Comment by tunnckoCore** [comment]
I also published https://github.com/tunnckoCore/base-request yesterday. I'll try to finish it later this evening. It only needs to get the `lib/utils` file and tests.

**Comment by doowb** [comment]
Oh... I saw the other PR comments first... Yeah, I'll take a look at both of these and get them merged today.

**Comment by tunnckoCore** [comment]
> get them merged today.

Thanks! Be aware of that this PR includes #11, sorry if this is a problem.

**Pull request closed without merging**
