### PR TITLE
externalize .requestAll to `request-all`

### PR DESCRIPTION
**Pull request by tunnckoCore**
I've just externalize `.requestAll` method from `lib/utils.js` to standalone lib that can be useful.
That [request-all](https://github.com/tunnckoCore/request-all) lib can be used as wrapper for `simple-get` or as standalone library, so pretty lil' changes was done in that PR. It can handle json and non-json response, also handles url normalization and default headers. 
It has only `parse-link-header` as dependency.

I also update reflinks and related links, but can't find ANY working verb that i can just install and run, so please run verb in your side, lol.

Cheers,
Charlike.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> I also update reflinks and related links, but can't find ANY working verb that i can just install and run, so please run verb in your side, lol.

yeah, don't try. lol I'll do it.

thanks, looks great to me! @doowb?

**Comment by doowb** [comment]
I like it!
I think this is good to merge.

**Comment by tunnckoCore** [comment]
> yeah, don't try. lol I'll do it.

haha, okey. Thanks!

**Comment by jonschlinkert** [comment]
yeah there is a bug with `.getAll` currently. This might resolve it, we can merge first then go from there. @doowb want to merge this too?

**Comment by doowb** [comment]
Yeah, I'll get this merged in today.

**Comment by tunnckoCore** [comment]
> there is a bug with .getAll currently.

What is the bug? 

> This might resolve it

Maybe. You can check the `request-all` tests. And if needed PR there :)

**Pull request closed without merging**
