### PR TITLE
Add param key in the Url when they are added in opts

### PR DESCRIPTION
**Pull request by tennisonchan**
### Problem
The key `params` is overridden in here https://github.com/jonschlinkert/github-base/blob/master/lib/utils.js#L126

Also, there is no place to add params in the Url.

### Solution
- Change the order of `params` placeholder when extending the options.
- Add param keys in the Url in function `createURL`

### CODE REVIEW

**Comment by doowb** [comment]
Thanks for the PR, but the order is intentional because that `params` array is used for holding the keys of the params found in the url. The params are things that start with a colon: e.g. `:foo` gets replaced with the value from `options.foo`.

If the goal is to be able to add query string key/value pairs, then you could do that before passing the url to the `.request` (or `.get` or `.paged`) method:

```js
github.get('/users?since=12345', ....);
```

We might consider using the `url` module to form the url and allow a `query` option to be passed in that will be used when building the query string.

**Comment by tennisonchan** [comment]
@doowb I understand that the `params` will later be used in the `cleanup ` function [here](https://github.com/tennisonchan/github-base/blob/81c7f6d634406883aec0be3d93a575ce92b7cff0/lib/utils.js#L192). Changing the order will not affect the functionality of this purpose, instead it allows the user to add params on the url.

Without this change, I cannot use `gists.all` with a github-supported param `since` [link](https://developer.github.com/v3/gists/#parameters) in the `gists` repo. Using `github.get('/gists?since=1234')` can work around the problem, but it defeats the purpose of the `gists` repo. It shows that `github-base` is not flexible enough for other libs to build on up.

Without affecting the original purpose of the `params` as a placeholder, it will be beneficial to make this change. What do you think?

**Comment by doowb** [comment]
I think that if we support a `query` option, then that can be used the way that you want to use `params`. Then it would look more like:

```js
github.get('/gists', {query: {since: 1234});
```

This will also match the [url.format](https://nodejs.org/api/url.html#url_url_format_urlobject) method.

This will allow users of the `gists` library to do `gists.all({query: {since: 12345}})`. Add, as a convenience in the `gists` library, we could update it to handle the `since` option directly to provide a nicer api: `gists.all({since: 12345})`.

**Comment by tennisonchan** [comment]
Aligning with node url format is a good approach 👍 

Thanks for suggesting the temporary work-around of `gists.all`, though I don't think it would be a good idea as there are many gists endpoints also supporting the param `since` and many more other params. This approach is not scalable and will introduce technical debts. Not a good tradeoff for the convenience it provides, imo.

This PR is for doing what I want to do with minimal changes. If it is not useful, please feel free to drop it and design it from scratch. Thanks!

**Pull request closed without merging**
